<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.3.5</version>
        <relativePath/>
    </parent>

    <groupId>cl.duoc.banco.bff</groupId>
    <artifactId>banco-bff-parent</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>
    <name>banco-bff-parent</name>
    <description>
        Banco XYZ - Implementacion del patron Backend for Frontend (BFF).
        Arquitectura con 3 BFFs independientes (web, mobile, atm) + backend-core
        + proceso batch (Spring Batch) sobre los datos legacy de bank_legacy_data.
    </description>

    <modules>
        <module>common</module>
        <module>auth-server</module>
        <module>backend-core</module>
        <module>banco-batch</module>
        <module>bff-web</module>
        <module>bff-mobile</module>
        <module>bff-atm</module>
        <module>notificaciones-service</module>
    </modules>

    <properties>
        <java.version>21</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.release>21</maven.compiler.release>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>cl.duoc.banco.bff</groupId>
                <artifactId>banco-bff-common</artifactId>
                <version>${project.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-maven-plugin</artifactId>
                    <configuration>
                        <excludes>
                            <exclude>
                                <groupId>org.projectlombok</groupId>
                                <artifactId>lombok</artifactId>
                            </exclude>
                        </excludes>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>
</project>
