spring.application.name=banco-bff-auth-server
server.port=9000

# Mensajeria asincrona (productor Kafka de eventos de autenticacion)
app.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}

logging.level.cl.duoc.banco.bff=DEBUG
logging.level.org.springframework.security=INFO
