spring.application.name=banco-bff-atm
server.port=8084

server.ssl.enabled=true
server.ssl.key-store-type=PKCS12
server.ssl.key-store=classpath:keystore/keystore.p12
server.ssl.key-store-password=banco123
server.ssl.key-alias=banco-bff
server.ssl.protocol=TLS
server.ssl.enabled-protocols=TLSv1.2,TLSv1.3

# ===================== Seguridad (OAuth 2.0) =====================
app.security.jwt.jwk-set-uri=${JWK_SET_URI:http://localhost:9000/oauth2/jwks}
app.oauth2.token-uri=${AUTH_SERVER_TOKEN_URI:http://localhost:9000/oauth2/token}
app.oauth2.client-id=${OAUTH2_CLIENT_ID:bff-atm-client}
app.oauth2.client-secret=${OAUTH2_CLIENT_SECRET:atm-secret}
app.oauth2.scope=atm
app.security.keystore=classpath:keystore/keystore.p12
app.security.keystore-password=banco123

# ===================== Comunicacion con backend-core =====================
backend-core.base-url=${BACKEND_CORE_URL:https://localhost:8081}
app.http.connect-timeout-ms=2000
app.http.read-timeout-ms=5000

# ===================== Tolerancia a fallos (Resilience4j) =====================
resilience4j.circuitbreaker.instances.backendCore.sliding-window-size=10
resilience4j.circuitbreaker.instances.backendCore.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.backendCore.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.backendCore.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.backendCore.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.backendCore.automatic-transition-from-open-to-half-open-enabled=true

resilience4j.retry.instances.backendCore.max-attempts=3
resilience4j.retry.instances.backendCore.wait-duration=500ms

logging.level.cl.duoc.banco.bff=DEBUG
