spring.application.name=banco-bff-atm
server.port=8084

server.ssl.enabled=true
server.ssl.key-store-type=PKCS12
server.ssl.key-store=classpath:keystore/keystore.p12
server.ssl.key-store-password=banco123
server.ssl.key-alias=banco-bff
server.ssl.protocol=TLS
server.ssl.enabled-protocols=TLSv1.2,TLSv1.3

app.security.jwt-secret=banco-xyz-super-secreto-jwt-hs256-compartido-2024
app.security.jwt-expiration-ms=3600000
app.security.jwt-issuer=banco-xyz-bff
app.security.keystore=classpath:keystore/keystore.p12
app.security.keystore-password=banco123

backend-core.base-url=${BACKEND_CORE_URL:https://localhost:8081}
app.http.connect-timeout-ms=2000
app.http.read-timeout-ms=5000

logging.level.cl.duoc.banco.bff=DEBUG
